---
  name: terraform
  
  on:
    workflow_dispatch:
      inputs:
        terraform_action:
          description: "Terraform action"
          type: choice
          required: true
          default: "plan"
          options:
            - "plan"
            - "apply"
            - "destroy"
  
  env:
    ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
    TF_VAR_deploy_ssh_public_key: ${{ vars.SSH_PUBLIC_KEY }}
  
  defaults:
    run:
      working-directory: terraform
  
  jobs:
    terraform:
      runs-on: ubuntu-latest
      steps:
        - name: "Check out the repository"
          uses: actions/checkout@v4
  
        - name: "Setup Terraform"
          uses: hashicorp/setup-terraform@v3
        
        - name: "Run terraform init"
          id: init
          run: "terraform init -no-color"
        
        - name: "Run terraform validate"
          id: validate
          run: "terraform validate -no-color"
    
        - name: "Run terraform plan"
          if: ${{ inputs.terraform_action == 'plan' || inputs.terraform_action == 'apply' }}
          id: plan
          run: "terraform plan -no-color -input=false -out tfplan"
    
        - name: "Run terraform apply"
          if: ${{ inputs.terraform_action == 'apply' }}
          id: apply
          run: "terraform apply -no-color -auto-approve -input=false tfplan"
  
        - name: "Run terraform destroy"
          if: ${{ inputs.terraform_action == 'destroy' }}
          id: destroy
          run: "terraform destroy -no-color -auto-approve -input=false"
